language: cpp

compiler:
  - gcc
  - clang

install:
# Use g++4.9 and not 4.6 (C++11 missing)
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
# Retrieve Google Test sources and compile it
  - git clone https://github.com/google/googletest.git gtest
  - cmake -Bgtest/googletest/build -Hgtest/googletest/
  - cmake --build gtest/googletest/build --config Release

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - clang

before_script:
  - cmake -DGTEST_INCLUDE_DIR:string=gtest/googletest/include -DGTEST_LIBRARY:string=gtest/googletest/build/Release/gtest.lib -DGTEST_MAIN_LIBRARY:string=gtest/googletest/build/Release/gtest_main.lib

script:
  - make
